apiVersion: v1
kind: Namespace
metadata:
  name: forkflow-local
  labels:
    name: forkflow-local
    environment: local
    app.kubernetes.io/part-of: forkflow-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    app.kubernetes.io/part-of: forkflow-platform
